# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a4797f38-148b-4ba5-8d63-d5055d5f3c8c";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/448217c7-3b83-4ac1-b0c7-5aea9e1b3f9b"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
